source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Sendpushlib_Example', :exclusive => true do
  pod "Sendpushlib", :path => "../"
  pod "JSONWebToken", '~> 1.4.0'
end

target 'Sendpushlib_Tests', :exclusive => true do
  pod "Sendpushlib", :path => "../"

  pod 'Quick', '~> 0.7.0'
  pod 'Nimble', '~> 2.0.0'
  pod ' ', '~> 2.0.6'

end
